apiVersion: v1
kind: Service
metadata:
  name: ebank-frontend
  namespace: ebank
spec:
  type: LoadBalancer
  selector:
    app: ebank-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80