apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebank-frontend
  namespace: ebank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ebank-frontend
  template:
    metadata:
      labels:
        app: ebank-frontend
    spec:
      containers:
        - name: ebank-frontend
          image: 047385030300.dkr.ecr.us-east-2.amazonaws.com/dev-ebank-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi