apiVersion: v1
kind: Service
metadata:
  name: ebank-django
  namespace: ebank
spec:
  type: ClusterIP
  selector:
    app: ebank-django
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000